name: Hello World CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:

jobs:
  say-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Hello World script
        run: echo "Hello, DevOps Team! 🚀"
